stages:
    - build
    - deploy

build-staging:
    image: docker:stable
    stage: build
    only:
        - develop
    services:
        - docker:dind
    before_script:
        - cp .env.staging .env
        - echo -e >> .env
        - echo "BASE_API=$BASE_API_STAGING" >> .env
        - echo "CLIENT_URL=$CLIENT_URL_STAGING" >> .env
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CONTAINER_STAGE_IMAGE .
        - docker push $CONTAINER_STAGE_IMAGE

deploy-staging:
    image: docker:stable
    stage: deploy
    only:
        - develop
    services:
        - docker:dind
    before_script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull $CONTAINER_STAGE_IMAGE
        - docker save $CONTAINER_STAGE_IMAGE > image.tar

        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
    script:
        - ssh $STAGE_SERVER "mkdir -p ~/web_company/"
        - scp image.tar docker-compose.yml $STAGE_SERVER:~/web_company/
        - ssh $STAGE_SERVER "cd ~/web_company/ && sudo docker load --input image.tar && sudo docker-compose -f docker-compose.yml down && sudo docker-compose -f docker-compose.yml up -d"

build-product:
    image: docker:stable
    stage: build
    only:
        - master
    services:
        - docker:dind
    before_script:
        - cp .env.product .env
        - echo -e >> .env
        - echo "BASE_API=$BASE_API_PRODUCT" >> .env
        - echo "CLIENT_URL=$CLIENT_URL_PRODUCT" >> .env
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build -t $CONTAINER_PRODUCT_IMAGE .
        - docker push $CONTAINER_PRODUCT_IMAGE

deploy-product:
    image: docker:stable
    stage: deploy
    only:
        - /^v_[0-9]+(?:.[0-9]+)+$/
    services:
        - docker:dind
    before_script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker pull $CONTAINER_PRODUCT_IMAGE
        - docker save $CONTAINER_PRODUCT_IMAGE > image.tar

        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - echo "$PRODUCT_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
    script:
        - ssh $PRODUCT_SERVER "mkdir -p ~/web_company/"
        - scp image.tar docker-compose-prod.yml $PRODUCT_SERVER:~/web_company/
        - ssh $PRODUCT_SERVER "cd ~/web_company/ && sudo docker load --input image.tar && sudo docker-compose -f docker-compose-prod.yml down && sudo docker-compose -f docker-compose-prod.yml up -d"
